### ISSUE TITLE
Requirements : ip2asn 

### ISSUE THREAD

**Issue by hayatbellafkih** [InternetHealthReport/tartiflette#4]
Hi,
I got this error
```
Traceback (most recent call last):
  File "rttAnalysis.py", line 37, in <module>
    import ip2asn 
ImportError: No module named ip2asn
```
Are you using this [ip2asn](https://github.com/romain-fontugne/ip2asn)   ?

Thanks in advance.

**Comment by romain-fontugne** [comment]
Yes, actually you should put it in a directory called ip2asn next to tartiflette
