### ISSUE TITLE
Computation of confidence interval with Wilson score 

### ISSUE THREAD

**Issue by hayatbellafkih** [InternetHealthReport/tartiflette#5]
Hello,

I am trying to correlate your approach with the given code (tartiflette), and I have some questions:

1. You are using the CLT theorem, you compute the median of the n samples, these samples are the differential RTTs for a given bin. So, your samples are based on the number of the differential RTT   of the analyzed link at a given bin. The CLT theorem said that the size of the samples should be same, how to guarantee this condition in your case?

2. In the paper : "_To account for uncertainty in the computed medians, we also calculate confidence intervals. In the case of the median, confidence intervals are usually formulated as a binomial calculation and are distribution free_" :

     2.1 - why the confidence intervals are usually formulated as a binomial calculation?
     2.3 - why confidence intervals are distribution free?
     2.4 - why you chose p as 0.5?

Thanks in advance.

**Comment by romain-fontugne** [comment]
Hi,
1. You are right we may have a varying number of samples. If the number is significantly varying we expect to have a forwarding anomaly for that link.

2. This is purely mathematics, please refer to https://newonlinecourses.science.psu.edu/stat414/node/316/
